import type { Metadata } from "next";
import { Nunito, Roboto } from "next/font/google";
import "./styles/globals.css";
import Providers from "./Providers";
import { Toaster } from "@/components/ui/toaster";
import Sidebar from "./components/Sidebar";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-roboto",
});

const nunito = Nunito({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-nunito",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} ${roboto.variable}  bg-main_background font-primary antialiased`}
      >
        <div className="flex ">
          <Sidebar />
          <div className="p-5 w-full">{children}</div>
          <Toaster />
        </div>
      </body>
    </html>
  );
}
